# Generated by Django 3.1.2 on 2020-10-10 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galla', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='images',
            new_name='img',
        ),
    ]
