# Generated by Django 3.1.2 on 2020-10-10 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galla', '0003_auto_20201011_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.TextField(max_length=400),
        ),
    ]
